@startuml
title "Тёплый дом" Контекстная диаграмма [Текущий монолит]

top to bottom direction

!includeurl ../C4_templates/C4_Context.puml

Person_Ext(user, "Пользователь", "Пользователь, в доме которого система отопления подключена к Warmhouse")
Person(specialist, "Специалист", "Специалист подключения, Специалист сопровождения или другой внутренний")

System(WarmhouseSystem, "Тёплый дом", "Управление и мониторинг системам отопления в домах")

System_Ext(controller, "Модуль управления отоплением", "Управляет системой отопления в доме")
System_Ext(sensor, "Датчик температуры", "Возвращает по запросу текущую температуру в доме")
System_Ext(NC, "Центр Нотификаций", "Отправляет SMS/Push/EMail указанным получателям")

Rel(user, WarmhouseSystem, "Управляет (вкл/выкл) системой отопления")
Rel(user, WarmhouseSystem, "Получает состояние системы отопления")
Rel(WarmhouseSystem,NC, "Уведомляет об изменении состояния системы отопления в доме используя")
Rel(NC,user,"Передает уведомления об изменении состояния системы отопления в доме")
Rel(specialist, WarmhouseSystem, "Управляет (вкл/выкл) системой отопления")
Rel(specialist, WarmhouseSystem, "Получает состояние системы отопления")
Rel(WarmhouseSystem,controller,"Управляет (вкл/выкл) системой отопления")
Rel(WarmhouseSystem,controller,"Получает состояние системы отопления")

Rel(user, WarmhouseSystem, "Получает текущую температуру в доме")
Rel(specialist, WarmhouseSystem, "Получает текущую температуру в доме")
Rel(WarmhouseSystem,sensor,"Получает показания температуры")

Rel(specialist, WarmhouseSystem, "Управляет подключением (подкл/откл) систем отопления к системе Теплый дом")

Rel(user, WarmhouseSystem, "Просматривает собственные перс данные и данные договоров")
Rel(user, WarmhouseSystem, "Просматривает и изменяет собственные аутентификационных данных")
Rel(WarmhouseSystem,NC, "Уведомляет об изменении персональных, аутентификационных данных, данных договоров используя")
Rel(NC,user,"Передает уведомления об изменении персональных, аутентификационных данных, данных договоров")
Rel(NC,specialist,"Передает уведомления об изменении аутентификационных данных")
Rel(specialist, WarmhouseSystem, "Просматривает и изменяет собственные аутентификационные данные")
Rel(specialist, WarmhouseSystem, "Регистрирует, изменяет полномочия и блокирует Пользователей и Специалистов")
Rel(specialist, WarmhouseSystem, "Просматривает и изменяет аутентификационные, персональные данные и данные договоров Пользователей")

@enduml